baseurl: https://memwey.github.io/
languageCode: zh-cn
paginate: 8
title: Mem.Wey's Github Pages

# Change it to your Disqus shortname before using
disqusShortname: memwey

# GA Tracking ID
googleAnalytics: UA-138801420-1

# Theme i18n support
# Available values: ar, ca, de, el, en, es, fr, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true
