### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
main:
  - identifier: home
    name: Home
    url: /
    weight: -100
    params:
      icon: home

social:
  - identifier: github
    name: GitHub
    url: https://github.com/memwey
    params:
      icon: brand-github

  - identifier: twitter
    name: Twitter
    url: https://twitter.com/Mem_Wey
    params:
      icon: brand-twitter
